#!/usr/bin/python
import sys


class Parser:
    def __init__(self, file_name):
        self.curr = -1
        self.commands = []
        self.command = ""
        file = open(file_name)
        for line in file:
            line = line.partition("//")[0]
            line = line.strip()
            if line:
                self.commands.append(line)
        file.close()

    # Check if we finished to parse the file
    def hasMoreLines(self):
        return (self.curr + 1) < len(self.commands)

    # Go to the next instruction and make it current
    def advance(self):
        if self.hasMoreLines():
            self.curr += 1
            self.command = self.commands[self.curr]

    # Returns a constant representing the type of the correct command
    def CommandType(self):
        commanding = self.command.split()[0]
        if "push" == commanding:
            return "C_PUSH"
        elif "pop" == commanding:
            return "C_POP"
        elif "add" or "sub" or "neg" or "eq" or "gt" or "lt" or "and" or "and" or "or" or "not" == commanding:
            return "C_ARITHMETIC"

    def arg1(self):
        if self.CommandType() == "C_POP" or self.CommandType() == "C_PUSH":
            return self.command.split()[1]

    def arg2(self):
        if self.CommandType() == "C_POP" or self.CommandType() == "C_PUSH":
            return int(self.command.split()[2])


class CodeWriter(object):

    def __init__(self, filename):
        name = filename.replace(".vm", ".asm")
        self.output_file = name  # Change the type of the file output to hack
        self.label = 0  # counting the labels
        self.output_file = open(self.output_file, "w")

    def writeArithmetic(self, command):
        CommandDictionary = {
            "add": "@SP\nAM=M-1\nD=M\n@SP\nAM=M-1\nM=D+M\n@SP\nM=M+1\n",
            "sub": "@SP\nAM=M-1\nD=M\n@SP\nAM=M-1\nM=M-D\n@SP\nM=M+1\n",
            "neg": "@SP\nA=M-1\nM=-M\n",
            "not": "@SP\nA=M-1\nM=!M\n",
            "or": "@SP\nAM=M-1\nD=M\n@SP\nA=M-1\nM=D|M\n",
            "and": "@SP\nAM=M-1\nD=M\n@SP\nA=M-1\nM=D&M\n",
            "eq": "@SP\nAM=M-1\nD=M\n@SP\nA=M-1\nD=M-D\nM=-1\n@eqTrue" + str(self.label) + "\nD;JEQ\n@SP\nA=M-1\nM=0\n("
                                                                                           "eqTrue" + str(
                self.label) + ")\n",
            "gt": "@SP\nAM=M-1\nD=M\n@SP\nA=M-1\nD=M-D\nM=-1\n@gtTrue" + str(self.label) + "\nD;JGT\n@SP\nA=M-1\nM=0\n("
                                                                                           "gtTrue" + str(
                self.label) + ")\n ",
            "lt": "@SP\nAM=M-1\nD=M\n@SP\nA=M-1\nD=M-D\nM=-1\n@ltTrue" + str(self.label) + "\nD;JLT\n@SP\nA=M-1\nM=0\n("
                                                                                           "ltTrue" + str(
                self.label) + ")\n "
        }
        if CommandDictionary[command] is not None:
            self.output_file.write(CommandDictionary[command])
            if command == "eq" or "lt" or "gt":
                self.label += 1

    def WritePushPop(self, command, segment, index):
        SegmentDictionary = {
            "constant C_PUSH": '@' + str(index) + '\nD=A\n@SP\nA=M\nM=D\n@SP\nM=M+1\n',
            "static C_PUSH": "@" + str(index) + "\nD=M\n@SP\nA=M\nM=D\n@SP\nM=M+1\n",
            "static C_POP": "@SP\nAM=M-1\nD=M\n@" + str(index) + "\nM=D\n",
            "pointer C_PUSH": "@" + str(index) + "\nD=A\n@3\nA=A+D\nD=M\n@SP\nA=M\nM=D\n@SP\nM=M+1\n",
            "pointer C_POP": "@" + str(index) + "\nD=A\n@3\nD=A+D\n@R13\nM=D\n@SP\nAM=M-1\nD=M\n@R13\nA=M\nM=D\n",
            "this C_PUSH": "@" + str(index) + "\nD=A\n@THIS\nA=M+D\nD=M\n@SP\nA=M\nM=D\n@SP\nM=M+1\n",
            "this C_POP": "@" + str(index) + "\nD=A\n@THIS\nD=M+D\n@R13\nM=D\n@SP\nAM=M-1\nD=M\n@R13\nA=M\nM=D\n",
            "that C_PUSH": "@" + str(index) + "\nD=A\n@THAT\nA=M+D\nD=M\n@SP\nA=M\nM=D\n@SP\nM=M+1\n",
            "that C_POP": "@" + str(index) + "\nD=A\n@THAT\nD=M+D\n@R13\nM=D\n@SP\nAM=M-1\nD=M\n@R13\nA=M\nM=D\n",
            "argument C_PUSH": "@" + str(index) + "\nD=A\n@ARG\nA=M+D\nD=M\n@SP\nA=M\nM=D\n@SP\nM=M+1\n",
            "argument C_POP": "@" + str(index) + "\nD=A\n@ARG\nD=M+D\n@R13\nM=D\n@SP\nAM=M-1\nD=M\n@R13\nA=M\nM=D\n",
            "local C_PUSH": "@" + str(index) + "\nD=A\n@LCL\nD=M+D\n@R13\nM=D\n@SP\nAM=M-1\nD=M\n@R13\nA=M\nM=D\n",
            "local C_POP": "@" + str(index) + "\nD=A\n@LCL\nA=M+D\nD=M\n@SP\nA=M\nM=D\n@SP\nM=M+1\n",
            "temp C_PUSH": "@" + str(index) + "\nD=A\n@5\nA=A+D\nD=M\n@SP\nA=M\nM=D\n@SP\nM=M+1\n",
            "temp C_POP": '@' + str(index) + '\nD=A\n@5\nD=A+D\n@R13\nM=D\n@SP\nAM=M-1\nD=M\n@R13\nA=M\nM=D\n'
        }
        com = segment + " " + command
        writer = SegmentDictionary[com]
        if writer is not None:
            self.output_file.write(writer)

    def close(self):
        self.output_file.close()


def main():
    file = sys.argv[1]
    parser = Parser(file)
    writer = CodeWriter(file)
    while parser.hasMoreLines():
        parser.advance()
        type = parser.CommandType()
        if type == "C_PUSH" or type == "C_POP":
            writer.WritePushPop(type, parser.arg1(), parser.arg2())
        elif type == "C_ARITHMETIC":
            writer.writeArithmetic(parser.command)
    writer.close()


if __name__ == "__main__":
    main()
